// Japanese Translations for Aircraft Specifications Database
const japaneseTranslations = {
    // Home Page
    'Aircraft Specifications Database': '航空機仕様データベース',
    'Explore detailed specifications, performance data, and technical information for aircraft from leading manufacturers worldwide': '世界をリードする製造業者の航空機の詳細仕様、性能データ、技術情報をご覧ください',
    'Explore Aircraft': '航空機を探索',
    'Browse by Aircraft Type': '航空機タイプ別に閲覧',
    'Select an aircraft type to explore specifications and performance data': '航空機タイプを選択して仕様と性能データをご覧ください',
    'Business Jet': 'ビジネスジェット',
    'Executive & Private Aviation': 'エグゼクティブ＆プライベート航空',
    'TurboProp Aircraft': 'ターボプロップ機',
    'Efficient Regional Transport': '効率的な地域輸送',
    'Piston Aircraft': 'ピストン機',
    'General Aviation': '一般航空',
    'Jet Airliner': 'ジェット旅客機',
    'Commercial Passenger Jets': '商用旅客機',
    'Piston Rotorcraft': 'ピストン回転翼機',
    'Light Helicopters': '軽量ヘリコプター',
    'Turbine Rotorcraft': 'タービン回転翼機',
    'Heavy & Medium Helicopters': '大型＆中型ヘリコプター',
    'What You\'ll Find': '提供内容',
    'Interactive Charts': 'インタラクティブチャート',
    'Visualize performance data with interactive graphs and comparisons': 'インタラクティブなグラフと比較で性能データを視覚化',
    'Detailed Specifications': '詳細仕様',
    'Comprehensive technical data including dimensions, weights, and capacities': '寸法、重量、容量を含む包括的な技術データ',
    'Performance Metrics': '性能指標',
    'Speed, range, ceiling, and fuel consumption data': '速度、航続距離、上昇限度、燃料消費データ',
    'High-Quality Images': '高品質画像',
    'Detailed photos and diagrams of each aircraft': '各航空機の詳細写真と図表',
    'About This Database': 'データベースについて',
    'Our comprehensive aircraft specifications database provides accurate, up-to-date information for aviation enthusiasts, professionals, and researchers. Each aircraft profile includes detailed technical specifications, performance data, and interactive visualizations to help you understand the capabilities and characteristics of modern and historical aircraft.': '当社の包括的な航空機仕様データベースは、航空愛好家、専門家、研究者向けに正確で最新の情報を提供します。各航空機プロファイルには、詳細な技術仕様、性能データ、インタラクティブな視覚化が含まれており、現代および歴史的な航空機の能力と特性を理解するのに役立ちます。',
    'Search aircraft...': '航空機を検索...',
    'Home': 'ホーム',
    'Aircraft Types': '航空機タイプ',
    
    // Business Jet Page
    'Business Jets': 'ビジネスジェット',
    'About Business Jets': 'ビジネスジェットについて',
    'Business jets are aircraft designed for transporting small groups of people in comfort and style. They range from light jets perfect for regional travel to ultra-long-range aircraft capable of intercontinental flights. Business jets offer flexibility, privacy, time savings, and access to smaller airports unavailable to commercial airlines.': 'ビジネスジェットは、少人数のグループを快適でスタイリッシュに輸送するために設計された航空機です。地域旅行に最適な軽量ジェットから、大陸間飛行が可能な超長距離機まで様々です。ビジネスジェットは、柔軟性、プライバシー、時間の節約、商用航空会社では利用できない小規模空港へのアクセスを提供します。',
    'Browse by aircraft size category below to find the perfect business jet for your mission requirements.': '以下の航空機サイズカテゴリーから、ミッション要件に最適なビジネスジェットをお探しください。',
    
    // Aircraft Categories
    'Light Business Jets': '軽量ビジネスジェット',
    'Midsize Business Jets': '中型ビジネスジェット',
    'Super Midsize Business Jets': '大型中距離ビジネスジェット',
    'Large Business Jets': '大型ビジネスジェット',
    'Ultra Long-Range Business Jets': '超長距離ビジネスジェット',
    
    // Common Terms
    'View Details': '詳細を見る',
    'Coming Soon': '近日公開',
    'Range': '航続距離',
    'Max Speed': '最大速度',
    'Passengers': '乗客数',
    'Up to': '最大',
    
    // Footer
    '© 2026 Aircraft Specifications Database. All rights reserved.': '© 2026 航空機仕様データベース. 全著作権所有.',
    'Data compiled from official manufacturer specifications and aviation databases.': '公式メーカー仕様および航空データベースからコンパイルされたデータ。',
    
    // Search
    'No aircraft found': '航空機が見つかりません',
    
    // Aircraft Types (for search results)
    'Large Business Jet': '大型ビジネスジェット',
    'Ultra Long-Range Business Jet': '超長距離ビジネスジェット',
    'Light Business Jet': '軽量ビジネスジェット',
    'Midsize Business Jet': '中型ビジネスジェット',
    'Super Midsize Business Jet': '大型中距離ビジネスジェット',
    
    // G550 Aircraft Page
    'Gulfstream G550': 'ガルフストリーム G550',
    'The Gulfstream G550, manufactured from 2003-2021, requires a 2 person crew and can transport up to 18 passengers. The aircraft has a maximum operating altitude of 15,545 m (51,000 ft), a normal cruise speed of 904 km/h (488 KTS), and a 12,501 km (6,750 NM) seats-full range.': 'ガルフストリーム G550は2003年から2021年まで製造され、2名の乗組員を必要とし、最大18名の乗客を輸送できます。最大運用高度は15,545m（51,000フィート）、通常巡航速度は904km/h（488KTS）、座席満席時の航続距離は12,501km（6,750NM）です。',
    
    // Tabs
    'Summary': '概要',
    'Cost': 'コスト',
    'Performance': '性能',
    'Avionics': 'アビオニクス',
    'Interior': '内装',
    'Exterior': '外装',
    
    // Summary Tab
    'Gulfstream G550 Summary': 'ガルフストリームG550概要',
    'Ferry Range': 'フェリー航続距離',
    'Ferry Flight Range': 'フェリー飛行航続距離',
    'Full Seat Range': '満席時航続距離',
    'Normal Cruise Speed': '通常巡航速度',
    'Maximum Passengers': '最大乗客数',
    'Cost of Acquisition': '取得コスト',
    'New Price': '新品価格',
    'General Specifications': '一般仕様',
    'Manufacturer': '製造元',
    'Gulfstream Aerospace': 'ガルフストリーム・エアロスペース',
    'Production Years': '生産年',
    '2003 - 2021': '2003年 - 2021年',
    'Units Produced': '生産機数',
    '~600 Aircrafts': '約600機',
    'Active Fleet': '運用中機数',
    '~550 Aircrafts': '約550機',
    'Cabin Dimensions': 'キャビン寸法',
    'Cabin Volume': 'キャビン容積',
    'Cabin Height': 'キャビン高さ',
    'Cabin Width': 'キャビン幅',
    'Cabin Length': 'キャビン長さ',
    'Payload & Fuel': 'ペイロード＆燃料',
    'Useful Payload w/ Full Fuel': '満タン時の有用ペイロード',
    'Total Baggage Capacity': '総荷物容量',
    'Fuel Capacity': '燃料容量',
    
    // Cost Tab
    'Gulfstream G550 Cost Analysis': 'ガルフストリームG550コスト分析',
    'Fuel cost: $4.25 per gallon | Hourly variable cost based on 450 annual hours': '燃料費：ガロンあたり4.25ドル｜年間450時間に基づく時間変動費',
    'Annual Flight Hours:': '年間飛行時間：',
    'Enter your planned annual flight hours to see customized cost projections': '計画された年間飛行時間を入力してカスタマイズされたコスト予測を確認',
    'Total Annual Cost Summary': '年間総コスト概要',
    'Annual Variable Cost': '年間変動費',
    'Annual Fixed Cost': '年間固定費',
    'Total Annual Budget': '年間総予算',
    'Cost Per Hour': '時間あたりコスト',
    'Hourly Variable Cost': '時間変動費',
    'Fuel (358 gal/hr @ $4.25/gal)': '燃料（358ガロン/時 @ 4.25ドル/ガロン）',
    'Airframe Maintenance': '機体メンテナンス',
    'Engine/APU Maintenance': 'エンジン/APUメンテナンス',
    'Crew/Catering/Misc': '乗組員/ケータリング/その他',
    'Total Hourly Variable': '時間変動費合計',
    'Crew Salary & Benefits': '乗組員給与＆福利厚生',
    'Crew Training': '乗組員訓練',
    'Hangar': '格納庫',
    'Insurance': '保険',
    'Miscellaneous Fixed': 'その他固定費',
    'Total Annual Fixed': '年間固定費合計',
    'Cost Breakdown Analysis': 'コスト内訳分析',
    'Variable Cost Breakdown': '変動費内訳',
    'Fixed Cost Breakdown': '固定費内訳',
    'Fuel': '燃料',
    'Airframe Maintenance': '機体メンテナンス',
    'Engine/APU Maintenance': 'エンジン/APUメンテナンス',
    'Crew/Catering/Misc': '乗組員/ケータリング/その他',
    
    // Performance Tab
    'Gulfstream G550 Performance': 'ガルフストリームG550性能',
    'Speed Performance': '速度性能',
    'Maximum Speed': '最大速度',
    'Long-Range Cruise': '長距離巡航',
    'Range Capabilities': '航続距離能力',
    'Maximum Range': '最大航続距離',
    'Service Ceiling': '上昇限度',
    'Rate of Climb': '上昇率',
    'Weight Specifications': '重量仕様',
    'Max Takeoff Weight': '最大離陸重量',
    'Max Landing Weight': '最大着陸重量',
    'Basic Operating Weight': '基本運用重量',
    'Fuel Consumption': '燃料消費',
    'Fuel Usage Per Hour': '時間あたり燃料使用量',
    'Fuel Weight': '燃料重量',
    'Runway Length Requirements': '滑走路長要件',
    'Runway Distance Requirements': '滑走路距離要件',
    'Balanced Field Length': 'バランスフィールド長',
    'Part 91 Takeoff': 'パート91離陸',
    'Part 135 Takeoff': 'パート135離陸',
    'Landing Distance': '着陸距離',
    'Interactive Range Map': 'インタラクティブ航続距離マップ',
    'Search Departure Airport:': '出発空港を検索：',
    'Search by airport name or code (e.g., Tokyo or HND)...': '空港名またはコードで検索（例：東京またはHND）...',
    'Search and select an airport to see the G550\'s range from that location': '空港を検索して選択し、その場所からのG550の航続距離を確認',
    
    // Interior Tab
    'Gulfstream G550 Interior': 'ガルフストリームG550内装',
    'Seating Configuration': '座席配置',
    'Typical Configuration': '標準構成',
    '13-16 passengers': '13-16名乗客',
    'Minimum Crew': '最小乗組員',
    '2 pilots': '2名パイロット',
    'Flight Attendants': '客室乗務員',
    '1-2 (optional)': '1-2名（オプション）',
    'Baggage & Storage': '荷物＆収納',
    'Internal Baggage': '内部荷物',
    'External Baggage': '外部荷物',
    'Cabin Features': 'キャビン機能',
    'Cabin Altitude @ FL510': 'キャビン高度 @ FL510',
    'Cabin Pressure': 'キャビン圧力',
    'Cabin Windows': 'キャビン窓',
    '14 large windows': '14個の大型窓',
    'Noise Level': '騒音レベル',
    '50 dB (cruise)': '50dB（巡航時）',
    'Interior Highlights': '内装ハイライト',
    
    // Exterior Tab
    'Gulfstream G550 Exterior': 'ガルフストリームG550外装',
    'Aircraft Dimensions': '航空機寸法',
    'Overall Length': '全長',
    'Wingspan': '翼幅',
    'Height': '高さ',
    'Wing Area': '翼面積',
    'Powerplant': 'パワープラント',
    'Engines': 'エンジン',
    '2× Rolls-Royce BR710': '2×ロールスロイス BR710',
    'Engine Model': 'エンジンモデル',
    'BR710C4-11': 'BR710C4-11',
    'Thrust Per Engine': 'エンジンあたり推力',
    'Total Thrust': '総推力',
};

// Export for use in main.js
if (typeof module !== 'undefined' && module.exports) {
    module.exports = japaneseTranslations;
}
